# Generated by Django 2.2.3 on 2019-07-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hikes', '0002_auto_20190712_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rattleSnake',
            field=models.IntegerField(default=0),
        ),
    ]
