# Generated by Django 2.2.3 on 2019-07-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hikes', '0004_auto_20190717_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='rattleSnake',
        ),
        migrations.AddField(
            model_name='vote',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to='Hikes.User'),
        ),
    ]
