# Generated by Django 2.2.3 on 2019-07-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hikes', '0005_auto_20190717_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rattleSnake',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
