# Generated by Django 2.2.3 on 2019-07-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hikes', '0006_auto_20190723_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rattleSnake',
            field=models.CharField(max_length=155),
        ),
    ]
