# Generated by Django 2.2.3 on 2019-07-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hikes', '0007_auto_20190723_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rattleSnake',
            field=models.IntegerField(default=0),
        ),
    ]
