# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-11 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hikes', '0010_auto_20190726_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mapKey',
            field=models.CharField(default='key=AIzaSyBjYhRDGmMvVz4zHppFaWkMLMuS_u_ZyXs', max_length=500),
        ),
    ]
