# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-11 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hikes', '0011_user_mapkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mapKey',
        ),
    ]
